### ISSUE TITLE
New version testing

### ISSUE THREAD

**Issue by Eloston** [ungoogled-software/ungoogled-chromium-macos#1]
The `master` branch should be ready for testing. Please try it out and let us know how it goes.

**Comment by Eloston** [comment]
Looks like CI checks are failing due to patches. If someone could update those, that'd be great.

**Comment by dajmon** [comment]
I had to change this line in build.sh in order to get the build going.
-_package_revision=$(cat $_root_dir/revision.txt)
+_package_revision=$(cat $_root_dir/ungoogled-chromium/revision.txt)

Build later failed on:
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ungoogled-chromium-macos/build/src/third_party/google_toolbox_for_mac/src'

**Comment by Eloston** [comment]
Looks like lines 19-20 are not working properly. Could you tell me what is in your `build/download_cache` directory?

**Comment by dajmon** [comment]
$ ls -l build/download_cache
total 571464
-rw-r--r--  1 dajmon  staff  290272140 Mar 29 08:43 clang+llvm-6.0.0-x86_64-apple-darwin.tar.xz
-rw-r--r--  1 dajmon  staff     381834 Mar 29 08:43 google-toolbox-for-mac-3c3111d3aefe907c8c0f0e933029608d96ceefeb.tar.gz

**Comment by dajmon** [comment]
I made some progress. I had to switch the downloads.ini to let chromium do it's thing before the toolbox and llvm.
```
-"$_main_repo/utils/downloads.py" retrieve -i "$_main_repo/downloads.ini" -i "$_root_dir/downloads.ini" -c "$_download_cache"
-"$_main_repo/utils/downloads.py" unpack -i "$_main_repo/downloads.ini" -i "$_root_dir/downloads.ini" -c "$_download_cache" "$_src_dir"
+"$_main_repo/utils/downloads.py" retrieve -i "$_root_dir/downloads.ini" -i "$_main_repo/downloads.ini" -c "$_download_cache"
+"$_main_repo/utils/downloads.py" unpack  -i "$_root_dir/downloads.ini" -i "$_main_repo/downloads.ini" -c "$_download_cache" "$_src_dir"
```
Build fails on the ninja stuff:
```
ninja: Entering directory `/Users/dajmon/Development/macOS/ungoogled-chromium-macos/build/src/out/Release/gn_build'
[175/175] LINK gn
+ ./out/Default/gn gen out/Default --fail-on-unused-args
Done. Made 9455 targets from 1570 files in 6201ms
+ ninja -C out/Default chrome chrome_sandbox chromedriver
ninja: Entering directory `out/Default'
ninja: error: unknown target 'chrome_sandbox'
```

**Comment by Eloston** [comment]
I made some pretty silly mistakes. Those should be fixed now.

**Comment by dajmon** [comment]
I had to adjust the revision.txt line in `build.sh` again otherwise it compiled successfully.
```
-_package_revision=$(cat $_root_dir/revision.txt)
+_package_revision=$(cat $_root_dir/ungoogled-chromium/revision.txt)
```

**Comment by saltama** [comment]
(Tested and it works flawlessly, compiling the untagged 73.x now)

(Thanks for all your work Eloston)
