### ISSUE TITLE
Build fails on 10.14.5

### ISSUE THREAD

**Issue by gubikmic** [ungoogled-software/ungoogled-chromium-macos#10]
Trying to build `74.0.3729.131-1.1`, it fails with the below message:

```

********************************************************************************
 WARNING: The Mac OS X SDK is incompatible with the version of Xcode. To fix,
          either upgrade Xcode to the latest version or install the Mac OS X
          10.13 SDK. For more information, see https://crbug.com/620127.

 Current SDK Version:   10.14
 Current Xcode Version: 1021 (10E1001)
********************************************************************************
ERROR at //build/config/mac/mac_sdk.gni:111:3: Assertion failed.
  assert(false, "SDK is incompatible with Xcode")
  ^-----
SDK is incompatible with Xcode
See //build/config/sysroot.gni:64:3: whence it was imported.
```

Do I just have to bump a variable from 10.13 to 10.14 somewhere? If so, where?

**Comment by saltama** [comment]
Can't try this since I'm not using the .15 beta, have you tried installing the latest Xcode beta?

**Comment by saltama** [comment]
Nvm, I've just received the update.

**Comment by saltama** [comment]
No error here (i've reached the `ninja -C out/Default chrome chromedriver` phase and compiled for a while), but i've just updated to 10.14.5 and left Xcode 10.21 untouched.
You can either temporarily set this variable before building:
```
export FORCE_MAC_SDK_MIN=10.14
```
Or directly change that value in `build/src/build/config/mac/mac_sdk_overrides.gni`, but it shouldn't be needed, it's still at 10.13 and it has always worked.
No idea what could be different in your setup.
