### ISSUE TITLE
Missing ARM64 build for 112.0.5615.49

### ISSUE THREAD

**Issue by VulpesVulpes825** [ungoogled-software/ungoogled-chromium-macos#107]
It seems the [GitHub Action](https://github.com/ungoogled-software/ungoogled-chromium-macos/actions/runs/4641674889#artifacts) did not produce the final installation file like [the x86 one](https://github.com/ungoogled-software/ungoogled-chromium-macos/actions/runs/4641688663) even though it is marking as complete.

**Comment by networkException** [comment]
Only needed two rebuilds :sweat_smile:
