### ISSUE TITLE
Google Voice in-call Audio Silent

### ISSUE THREAD

**Issue by resolutecake** [ungoogled-software/ungoogled-chromium-macos#120]
Google Voice in-call Audio Silent
— used to work until maybe a month ago (7/2023)

Discovered macOS 13.4.1.(c) Chromium 114.0.5735.198
Also present: macOS 13.5 Chromium 115.0.5790.170 (Official Build, ungoogled-chromium) (arm64)
works with macOS 13.5 Safari 16.6 (18615.3.12.11.2)

browse to: https://voice.google.com, place call
BUG: in-call audio in/out is silent
— ringing and hang-up sounds work
— listen to voicemail works
— audio test functions work

A periodical problem since 2019 when things no work related to some voice Plugin

**Comment by ahmed-aissam** [comment]
I'm having this exact same problem in Windows on the latest x64 version.

**Comment by PF4Public** [comment]
@resolutecake Have you tried latest version?

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently and probably lost its significance — closing.
If you have any more information to add, let us know.
