### ISSUE TITLE
Will there be new versions for macos? 

### ISSUE THREAD

**Issue by ahmetcadirci25** [ungoogled-software/ungoogled-chromium-macos#122]
A few releases behind. I hope you will release new versions as soon as possible?

**Comment by PF4Public** [comment]
https://github.com/ungoogled-software/ungoogled-chromium-macos/pull/119#issue-1837885892

**Comment by PF4Public** [comment]
I don't use Mac and therefore cannot suggest anything.

**Comment by PF4Public** [comment]
https://github.com/ungoogled-software/ungoogled-chromium-macos/pull/124

**Comment by ahmetcadirci25** [comment]
I think the update is in progress. so where can I download the new version.

**Comment by ahmetcadirci25** [comment]
where can I download the new version. @hlgsdx @PF4Public

**Comment by Cubik65536** [comment]
> > where can I download the new version. @hlgsdx @PF4Public
> 
> PR of v118 is approved and will be merged soon (#129)

It seems that two x86_64 builds were released for that version and there's no arm64 one?

**Comment by networkException** [comment]
that's still building https://github.com/ungoogled-software/ungoogled-chromium-macos/actions/runs/6581318616.

**Comment by ahmetcadirci25** [comment]
I think the updates have stopped again.

**Comment by Cubik65536** [comment]
@ahmetcadirci25 `119.0.6045.199` for x86 is now released. arm is [on the way coming](https://github.com/ungoogled-software/ungoogled-chromium-macos/actions/runs/7077727357).

**Comment by ahmetcadirci25** [comment]
> @ahmetcadirci25 `119.0.6045.199` for x86 is now released. arm is [on the way coming](https://github.com/ungoogled-software/ungoogled-chromium-macos/actions/runs/7077727357).

thank you.
