### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by tsuliwaensis** [ungoogled-software/ungoogled-chromium-macos#136]
When attempting to compile the build, I keep getting the error:

````
FAILED: gen/chrome/browser/resources/about_sys/preprocessed/app.html.ts gen/chrome/browser/resources/about_sys/preprocessed/app.html.ts 
python3 ../../tools/polymer/html_to_wrapper.py --in_folder gen/chrome/browser/resources/about_sys/preprocessed --out_folder gen/chrome/browser/resources/about_sys/preprocessed --in_files app.html log_entry.html --minify
Traceback
...
subprocess.CalledProcessError: Command '['which', 'node']' returned non-zero exit status 1
[533/57706] ACTION //chrome/browser/metrics:expired_histograms_array(//build/toolchain/mac:clang_x64)
````
What could be causing this issue?

**Comment by PF4Public** [comment]
It cannot find node.

**Comment by tsuliwaensis** [comment]
Thank you! I thought I had it installed but it was an older version that never upgraded due to a permission issue. 

However, I'm now running into this error
`No such file or directory: '/ungoogled-chromium-macos/patches/series'`

Is this something to do with refreshing the patches because I can't get that to work either. 

I'm new to all this so I apologize for the newbie questions

**Comment by PF4Public** [comment]
> No such file or directory: '/ungoogled-chromium-macos/patches/series'

Check where you've unpacked everything it cannot find this folder.

**Comment by tsuliwaensis** [comment]
Thank you again. I started from the beginning and the build compiled. 

If I may ask another question: What is the purpose of refreshing the patches? Is that something I will have to do to maintain my build?

**Comment by PF4Public** [comment]
> What is the purpose of refreshing the patches? 

It is used to update every offset in patch file to ensure it applies cleanly without fuzz

>Is that something I will have to do to maintain my build?

No

**Comment by tsuliwaensis** [comment]
Thanks for all your help.
