### ISSUE TITLE
`(Error code: 9) (Extra code: 0)` in About Chromium page

### ISSUE THREAD

**Issue by Cubik65536** [ungoogled-software/ungoogled-chromium-macos#145]
This issue is used to track the following issue and inform ungoogled-chromium macOS users about this (as it was reported before).

---

An error message with code `(Error code: 9) (Extra code: 0)` is shown in the about page since PR #134 (update to v120). (Check the photo below).

![image](https://github.com/ungoogled-software/ungoogled-chromium-macos/assets/72877496/a069c41a-d232-44d6-bfd1-96157185afc6)

It does also happen with official Google Chromium macOS builds. The same error is shown with the official build (while testing on my local environment) and there's multiple reports found online like [this one](https://stackoverflow.com/questions/77884106/how-can-i-solve-chromium-update-error-code-9-extra-code-0).

![image](https://github.com/ungoogled-software/ungoogled-chromium-macos/assets/72877496/db1d4065-09fb-4fe0-bfb7-a77654bfc240)

It's either an upstream issue or intended (as the update is disabled with vanilla Chromium). If it is intended, what's weird is that only macOS builds have the error message...

**Comment by PF4Public** [comment]
Granted it is cosmetic, could we patch it somehow?

**Comment by Cubik65536** [comment]
> Granted it is cosmetic, could we patch it somehow?

I haven't found any way to patch this for now... Will still investigate into this, but it's not on priority.

**Comment by Cubik65536** [comment]
Update: I don't know if #102 which

> disables the updater

have an influence on this. Will try this out soon.

**Comment by Cubik65536** [comment]
Result: YES.

Enable the updater will prevent this issue, but Chromium will continuously check update...

**Comment by PF4Public** [comment]
> Enable the updater will prevent this issue, but Chromium will continuously check update...

Perhaps it would be possible to hard-code a `return` in place of the check?

**Comment by Cubik65536** [comment]
> > Enable the updater will prevent this issue, but Chromium will continuously check update...
> 
> Perhaps it would be possible to hard-code a `return` in place of the check?

That's what I plan to do, but I'll have to find the check code...

**Comment by Cubik65536** [comment]
Should be gone if you updates to https://github.com/ungoogled-software/ungoogled-chromium-macos/releases/tag/126.0.6478.126-1.1 /cc @jorgehezd
