### ISSUE TITLE
Ungoogled Arc Browser

### ISSUE THREAD

**Issue by drkhero** [ungoogled-software/ungoogled-chromium-macos#160]
Would you guys ever consider making an "Ungoogled Arc Browser" ?

Basically, Arc Browser, but with all the spyware features removed just like for Ungoogled Chromium.

**Comment by Cubik65536** [comment]
> Would you guys ever consider making an "Ungoogled Arc Browser" ?
> 
> Basically, Arc Browser, but with all the spyware features removed just like for Ungoogled Chromium.

Unless Arc open sources all their code, no, we will not be able to do it.

**Comment by drkhero** [comment]
> > Would you guys ever consider making an "Ungoogled Arc Browser" ?
> > Basically, Arc Browser, but with all the spyware features removed just like for Ungoogled Chromium.
> 
> No because it is out-of-scope of the project.
> 
> And it is not possible anyway unless The Browser Company open sources all their codes.

would it not be possible to decompile it?

**Comment by Cubik65536** [comment]
> > > Would you guys ever consider making an "Ungoogled Arc Browser" ?
> > > Basically, Arc Browser, but with all the spyware features removed just like for Ungoogled Chromium.
> > 
> > 
> > No because it is out-of-scope of the project.
> > And it is not possible anyway unless The Browser Company open sources all their codes.
> 
> would it not be possible to decompile it?

1. Have you tried it?
2. I doubt if this is legal.

**Comment by drkhero** [comment]
> > > > Would you guys ever consider making an "Ungoogled Arc Browser" ?
> > > > Basically, Arc Browser, but with all the spyware features removed just like for Ungoogled Chromium.
> > > 
> > > 
> > > No because it is out-of-scope of the project.
> > > And it is not possible anyway unless The Browser Company open sources all their codes.
> > 
> > 
> > would it not be possible to decompile it?
> 
>     1. Have you tried it?
> 
>     2. I doubt if this is legal.



> > would it not be possible to decompile it?
> 
> Have you attempted to do so? What are your results?

No, I'm not a swift/C++ developer, this is why I came here to ask.

**Comment by Cubik65536** [comment]
> No, I'm not a swift/C++ developer, this is why I came here to ask.

Then I already told you the answer, which is **no**.

I am not aware of any decompiler that decompiles Swift (or even C++) built binaries straight into source. A decompiler exists, but what came out of it is usually not helpful unless lots of manual work are put into the reverse engineering work.

Again, reverse engineer a product is not in the scope of the project, even though it contains Chromium. Providing another ungoogled browser isn't. **This is the first thing I told you.**

I'm not a lawyer, and I don't spend my time reading laws, but I do believe reverse engineer some company's proprietary software to provide a modified version of it is not legal effectively anywhere.

So, TL;DR: **NO**.
