### ISSUE TITLE
Incoming network connections firewall permission prompts on every launch

### ISSUE THREAD

**Issue by pastmaster007** [ungoogled-software/ungoogled-chromium-macos#17]
## Issue
this morning, i built new chromium on my machine using commit id `73e79586cb25136feb2a197efbbfe17d2d287eb5`. 
chromium version: `75.0.3770.90-1.2`

everything builds fine and after system restart, chromium keeps on prompting for incoming network connections permission. Even though `i deny/allow keeps on prompting for permission on each launch`.

<img width="532" alt="B-172-incoming-messages-prompt" src="https://user-images.githubusercontent.com/43329756/59958366-e0da8a00-9494-11e9-9455-42b6e2a28008.png">

## Workaround:

applied code signing on chromium.app using below command and prompt was only for one time.
`sudo codesign --force --deep --sign - /Applications/Chromium.app`

Looks like we need to add above code signing part of build. This requires `sudo` command, is it okay to include as part of `build.sh` file? If so, we should add below command in build.sh file @ line 33 before packaging starts.
`sudo codesign --force --deep --sign - out/Default/Chromium.app`

**Comment by Eloston** [comment]
What key will this use to sign? Is there a way to do this without sudo?

**Comment by pastmaster007** [comment]
In the above command `-` refers Ad-hoc signing. As per `man`
> Ad-hoc signing does not use an identity at all, and identifies exactly
     one instance of code. Significant restrictions apply to the use of ad-hoc
     signed code; consult documentation before using this.

> codesign will attempt to embed the entire certificate chain documenting
     the signing identity in the code signature it generates, including any
     intermediate certificates and the anchor certificate.

Looks like we can use below two commands instead of `sudo`.

clears extended file attributes of app bundle and its internal files
`xattr -cr out/Default/Chromium.app`

apply ad-hoc signing to all files and folders in app bundle.
`codesign --force --deep --sign - out/Default/Chromium.app`

**Comment by macvip** [comment]
When building, 
`xattr -cr out/Default/Chromium.app` 
output:
`xattr: No such file: out/Default/Chromium.app/Contents/Frameworks/Chromium Framework.framework/Libraries`
The "Libraries" is a symbolic link to "Versions/Current/Libraries", so `xattr` needs the `-s` switch to avoid this error.
 `xattr -csr out/Default/Chromium.app`
