### ISSUE TITLE
Unable to install extension using the bookmarklet

### ISSUE THREAD

**Issue by MrChocolatine** [ungoogled-software/ungoogled-chromium-macos#174]
As far as I remember I have always used the bookmarklet for your FAQ to install extensions from the Chrome Web Store:
- https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#downloading-the-crx-file

However, for a few versions now I have not been able to install extensions using that bookmarklet.
I thought new versions would fix this but no. (I am currently running v126.0.6478.126 , latest versions available for MacOS)

Is something broken with Ungoogled-Chromium?
Is there any new step that I am not aware of?

Thank you.

**Comment by PF4Public** [comment]
You'd better provide more information. Have you tried installing the extension without bookmarklet?

**Comment by networkException** [comment]
Can you try the version from https://github.com/ungoogled-software/ungoogled-chromium-wiki/pull/31?

**Comment by MrChocolatine** [comment]
> You'd better provide more information. Have you tried installing the extension without bookmarklet?
@PF4Public 

Yes, same result.
The bookmarklet uses the same URL provided in the FAQ.

> Can you try the version from https://github.com/ungoogled-software/ungoogled-chromium-wiki/pull/31?
@networkException 

I tried the new URL proposed in that PR, installing extension seems to work again however if an extension already exists it is not replaced (the current installed version stays).

But if I uninstall an extension then use the new bookmarklet, the extension is properly installed (with the new version).

**Comment by MrChocolatine** [comment]
See https://github.com/ungoogled-software/ungoogled-chromium-wiki/pull/31 .
