### ISSUE TITLE
Installed PWAs not working on 130.0.6723.58-1.1

### ISSUE THREAD

**Issue by MicahBird** [ungoogled-software/ungoogled-chromium-macos#196]
Greetings! I'm a long time enjoyer of ungoogled-chromium, and love everything that this project does! 

I'm not sure if this a bug on my end, but ever since updating to 130.0.6723.58-1.1 (ARM64), I'm unable to open any pages that have been installed as apps from the "Install Page as App..."  menu. (Three Dots in the upper right > Cast, Save, and Share > Install Page as App...)

When attempting to open the app from macOS or from the `chrome://apps/` menu, the following error occurs. I've attempted the remedy `xattr -cr /Path/To/App.app`, however that doesn't seem to change anything. Interestingly the app still functions if you uncheck the "Open in window" option in `chrome://apps/`
![image](https://github.com/user-attachments/assets/32e4374d-287c-4622-b477-12e57e8a736e)

Steps to reproduce:

1. Go to `https://lite.duckduckgo.com/lite` (or any other page)
2. Click the Three Dots in the upper right > Cast, Save, and Share > Install Page as App...
3. Attempt to open the newly installed shortcut.

Any ideas or help would be greatly appreciated!

**Comment by Cubik65536** [comment]
I cannot reproduce this issue with upcoming 130.0.6723.69.

![CleanShot 2024-10-27 at 01 45 12](https://github.com/user-attachments/assets/43d84a5b-ffba-479d-b273-61ba808e823b)

Please wait till 130.0.6723.69 is release and try again, if it is still not working, please try with vanilla chromium and see if that behaves the same.

**Comment by marlonjames71** [comment]
I ran into the same issue with the very latest release (signed version).

**Comment by PF4Public** [comment]
maybe you need to recreate them since the binary is now signed?

**Comment by MicahBird** [comment]
> maybe you need to recreate them since the binary is now signed?

I'm afraid I already tried that multiple times to no avail. Thanks for the suggestion though! I shall eagerly await the next release! :)

**Comment by Cubik65536** [comment]
> I cannot reproduce this issue with upcoming 130.0.6723.69.
> 
> ![CleanShot 2024-10-27 at 01 45 12](https://private-user-images.githubusercontent.com/72877496/380470717-43d84a5b-ffba-479d-b273-61ba808e823b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNTUwNTgsIm5iZiI6MTczMDA1NDc1OCwicGF0aCI6Ii83Mjg3NzQ5Ni8zODA0NzA3MTctNDNkODRhNWItZmZiYS00NzlkLWIyNzMtNjFiYTgwOGU4MjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDE4NDU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyNmQwMzQ4ZDVmNTRiYTI0MjRjZmMzZjRhZWNkMjhlYjZiMTY5YTk0OWFiNjFkNjY3YTZhNjFjYzY2ODdlZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IrIWxJnfs6dwbSgxpryqIGc4u0ZBTrCQaGQFxSutbbo)
> 
> Please wait till 130.0.6723.69 is released and try again, if it is still not working, please try with vanilla chromium and see if that behaves the same.

I tested this with newly added "Chromium App", this might also be the reason why it worked. Another solution might be doing a clean uninstallation of Chromium and these PWAs (using some 3rd party tools, **but please make sure your saved bookmarks, passwords, etc. are BACKED UP**), and retry...

**Comment by MicahBird** [comment]
Unfortunately upon updating to 130.0.6723.69, I'm still experiencing this same issue... I've tried removing the entire `~/Applications/Chromium\ Apps.localized` and re-adding a PWA to no success either... I've also tried `xattr -cr *` in that folder but that did not work either sadly. Any further ideas/help would be greatly appreciated!

**Comment by Cubik65536** [comment]
> Unfortunately upon updating to 130.0.6723.69, I'm still experiencing this same issue... I've tried removing the entire `~/Applications/Chromium\ Apps.localized` and re-adding a PWA to no success either... I've also tried `xattr -cr *` in that folder but that did not work either sadly. Any further ideas/help would be greatly appreciated!

The way I can think of is to use tools, like https://github.com/alienator88/Pearcleaner (I am personally using it), to **completely uninstall everything (the app can find) about Chromium and Chromium Apps, and reinstall it.

Just be aware that your bookmarks, passwords, history, etc. will be lost. **BACK UP** bookmarks and passwords before.

**Comment by anttironty** [comment]
Fix for this is on macos is as follows:

1. Install PWA and select Cancel when prompted to move it to trash
2. Open System Settings
3. Privacy & Security
4. Scroll down to Security section
5. See this message "{PWA Name} was blocked to protect your Mac."
6. Select "Open anyway" next to that message

**Comment by MicahBird** [comment]
> Fix for this is on macos is as follows:
> 
>     1. Install PWA and select Cancel when prompted to move it to trash
> 
>     2. Open System Settings > Privacy & Security
> 
>     3. Scroll down to Security section
> 
>     4. See this message "{PWA Name} was blocked to protect your Mac."
> 
>     5. Select "Open anyway" next to that message

Woah. I'm genuinely shocked, that worked! I would have thought that `xattr -cr DuckDuckGo.app ` would do the trick, but apparently not... Thank you kindly! :)

**Comment by dumbmoron** [comment]
I think it would make sense to reopen this issue, since this: https://github.com/ungoogled-software/ungoogled-chromium-macos/issues/196#issuecomment-2459845079 is just a workaround. The real root cause is:

https://issues.chromium.org/issues/40251739

> Trying to find additional differences we noticed that in a Chrome-created PWA, right before the log that returns the evaluateScanResult, there's a log that says something about some tamper exception:
> 
> Bundle has tamper exception: PST: (path: /Users/user/Applications/Chrome Apps.localized/Google Maps.app), (team: EQHXZ8M8AV), (id: app_mode_loader), (bundle_id: com.google.Chrome.app.mnhkaebcjjhencmpkapnbdaogjamfbcj)
> 
> Trying to understand the difference in evaluateScanResult and what tamper exception is, we examined syspolicyd and discovered a Plist file at /var/db/SystemPolicyConfiguration/TamperExceptions.plist that includes Bundle IDs and Team IDs of what appears to be the tamper exception list. When we grepped this file for app_mode_loader, we saw that it actually includes the Team IDs of Google, Microsoft, and Brave.

I am currently looking into whether it would be possible to get added onto this list on request.
