### ISSUE TITLE
Update to 73

### ISSUE THREAD

**Issue by Eloston** [ungoogled-software/ungoogled-chromium-macos#2]
Help wanted for updating to ungoogled-chromium 73. Please respond if you'd like to work on this. Thanks

**Comment by dajmon** [comment]
I would like to help but my knowledge is limited in this field. Currently trying to get the patches working. Can't seem to get around the swiftshader dependency:
```
+ ./out/Default/gn gen out/Default --fail-on-unused-args
ERROR Unresolved dependencies.
//chrome:swiftshader_binaries(//build/toolchain/mac:clang_x64)
  needs //ui/gl:swiftshader_library_copy(//build/toolchain/mac:clang_x64)
//content/shell:content_shell_swiftshader_binaries(//build/toolchain/mac:clang_x64)
  needs //ui/gl:swiftshader_library_copy(//build/toolchain/mac:clang_x64)
```

**Comment by saltama** [comment]
Question, since it looks like that the stuff in `patches` should be the macOS specific stuff that only applies to this platform, should `patches/debian_buster/` be here? Or we need to look at those patches and remove what shouldn't be here?

(2-3 patches from there don't apply correctly, that's why i'm asking)

**Comment by dajmon** [comment]
https://github.com/dajmon/ungoogled-chromium-macos/commit/8c173b9fa7843c2af72879a2d089382e77623430
Had to update to clang 8.0.0 (never tried 7.0.0) to get rid of some compile errors. Modified some patches. Unsure of the mojo patch, removed more than i wanted.

**Comment by Eloston** [comment]
@saltama All patches in this repo are to be used for macOS. The names under `patches/` specifies where the patches came from. I don't have any specific requirements about where patches come from; you can add/remove patches as you see fit.

@dajmon Feel free to submit a PR when you're ready. FYI, I merged new changes into the main ungoogled-chromium repo not too long ago.

Also, I'm not sure how to coordinate both of your efforts. Thoughts?

**Comment by saltama** [comment]
I've thrown away the half done stuff I had so @dajmon can move forward if he wants.
I'll test it as soon as it lands and let me know if there is something else for me to do.

On the mojo patch, it looks like the old patch removed everything that was referring to "mojo", so in this case we could remove `//content/test:mojo_web_test_bindings` and `//content/test:web_test_support` too. If you don't want to rebuild it again, I could do it.

Also, what about `fix-disk_image_type_sniffer_mac.patch`? I've noticed it didn't apply correctly but haven't looked why.

**Comment by dajmon** [comment]
Ok, @saltama I will add your suggestions to the `mojo.patch` and create a pull request.
I removed the `fix-disk_image_type_sniffer_mac.patch` since it was not needed anymore.

**Comment by Eloston** [comment]
So there are two more things before I think this can be considered done:

* I added instructions for updating/refreshing patches, based on what I have done for `ungoogled-chromium-debian`
* There's a new version of ungoogled-chromium that I just merged in here (patches need to be refreshed)

Let me know how it goes.

**Comment by dajmon** [comment]
@Eloston I don't know if i do anything wrong here but `./devutils/update_patches.sh merge` gave me `./devutils/update_patches.sh: line 8: /Users/dajmon/Development/MacOS/ungoogled-chromium-macos/devutils/upstream/ungoogled-chromium/devutils/update_platform_patches.py: No such file or directory`
Also worth mentioning that you need to run `brew install quilt`

**Comment by saltama** [comment]
>`./devutils/update_patches.sh: line 8: /Users/dajmon/Development/MacOS/ungoogled-chromium-macos/devutils/upstream/ungoogled-chromium/devutils/update_platform_patches.py: No such file or directory`

See #4.

**Comment by dajmon** [comment]
@saltama Perfect, thanks! I also have .103 ready. What are your thoughts of removing `debian_buster/gpu-timeout.patch` and `debian_buster/include.patch ` as they seem to be linux-specific?

**Comment by saltama** [comment]
Yeah, we can delete both, as the whole `debian_buster/arm` directory.

**Comment by Eloston** [comment]
New tag published. Thanks @saltama @dajmon
