### ISSUE TITLE
Can't open installed Progressive Web Apps 

### ISSUE THREAD

**Issue by mryoaz** [ungoogled-software/ungoogled-chromium-macos#204]
Progressive Web Apps that are installed crashes on startup. The website in the normal ungoogled chromium window is working fine. But opening it's specific app will cause an error.

**Steps to reproduce**

1. Go to https://www.pwabuilder.com/
2. Click the install icon and install it
3. The app wil open
4. See the error window from macos: 
“PWABuilder” is damaged and can’t be opened. You should move it to the Bin.

Version: 130.0.6723.116

**Comment by Cubik65536** [comment]
See #196.
