### ISSUE TITLE
Updates through the app?

### ISSUE THREAD

**Issue by marlonjames71** [ungoogled-software/ungoogled-chromium-macos#211]
Is there a way to get updates through the app/browser itself?

I know Sparkle is commonly used for this for mac apps. Can something like this be implemented?

**Comment by Cubik65536** [comment]
I recommend using Homebrew (`brew install --cask eloston-chromium`, it is [here](https://github.com/ungoogled-software/ungoogled-chromium#downloads)) and periodically update your brew casks. No plugin or in-browser feature will likely be implemented by myself at least.

https://github.com/claudiodekker/chromium-update-notifier might be useful, but I don't guarantee anything.

**Comment by marlonjames71** [comment]
Okay thanks.
