### ISSUE TITLE
Enable CFI

### ISSUE THREAD

**Issue by CrossRoast** [ungoogled-software/ungoogled-chromium-macos#214]
[Vanadium](https://github.com/GrapheneOS/Vanadium/blob/44c6c2c60882569f157731b78d435a2deb504e4b/args.gn), which also runs on arm64, enables is_cfi and use_cfi_cast. Perhaps those options should be enabled for MacOS too for improved security.

**Comment by CrossRoast** [comment]
> https://www.chromium.org/developers/testing/control-flow-integrity/ it's only for Linux and Android

The page seems to imply it only works on Linux on x86, yet it works on Android (arm64). It might work on MacOS too in that case.

**Comment by Cubik65536** [comment]
I believe this is a discussion to be made in https://github.com/ungoogled-software/ungoogled-chromium as my goal is to make macOS build stay the same with the other OS ones. /cc @networkException

And, as that page doesn't explicitly mention that macOS is supported, I tend to not enable it here, unless we know that official Chromium is built with it as one of the [project philosophy](https://github.com/ungoogled-software/ungoogled-chromium#motivation-and-philosophy) says:

> ungoogled-chromium retains the default Chromium experience as closely as possible
