### ISSUE TITLE
Github CI dropping support for macos-10.14

### ISSUE THREAD

**Issue by saltama** [ungoogled-software/ungoogled-chromium-macos#37]
Just a heads up, GitHub is upgrading the macOS environment to Catalina, moving forward the only available environment value will be `macos-latest` and older releases will NOT be supported.
The migration is ongoing, so, sooner or later CI will start to fail as for #31.

**Comment by saltama** [comment]
Ok, the last few jobs I've run were running on Catalina...

**Comment by Zoraver** [comment]
I think this can safely be closed since ungoogled-chromium-macos has compiled on macOS 10.15 (and thus on Github CI) for a while now.
