### ISSUE TITLE
auto update?

### ISSUE THREAD

**Issue by Chippel** [ungoogled-software/ungoogled-chromium-macos#41]
I'd like to use this Software but I don't know if the Software updates itself. Do you guys provide any tool for auto updating this?

**Comment by Eloston** [comment]
You can install it via Homebrew as `eloston-chromium`: https://github.com/Eloston/ungoogled-chromium#downloads

Otherwise I don't know of any updating tool.

**Comment by SimonBrazell** [comment]
My solution for this is to install it via Homebrew, as @Eloston suggests, and then use [brew-autoupdate](https://github.com/DomT4/homebrew-autoupdate) to keep it up to date without any intervention needed by myself.

**Comment by Eloston** [comment]
That looks like a decent solution, thanks. Closing.
