### ISSUE TITLE
filter_libtool.py error with libsafe_browsing.a

### ISSUE THREAD

**Issue by Eloston** [ungoogled-software/ungoogled-chromium-macos#47]
Context: https://github.com/Eloston/ungoogled-chromium/issues/301#issuecomment-613466948

@HarukaMa Are you doing a component build (`is_component_build=true`)?

**Comment by HarukaMa** [comment]
Yes I am.

**Comment by HarukaMa** [comment]
I was trying to build a new version and this time I've turned off component build to use webrtc, however it seems this issue is still present.

My args.gn this time w/o common part:

```
blink_symbol_level = 0
symbol_level = 0
is_component_build = false
is_official_build = true
is_debug = false
proprietary_codecs = true
ffmpeg_branding = "Chrome"
```

**Comment by Eloston** [comment]
Hmm, that's interesting. Chances are there's still some references to the Safe Browsing component in GN that we'd need to remove.

Based on https://github.com/Eloston/ungoogled-chromium/issues/301#issuecomment-352159051, here's what you can try. After applying patches, you could look through `*.gn` files to see if there's still any remaining references to `//chrome/browser/safe_browsing` target, or any other targets named with `safe_browsing`. Most likely the GN files you need to modify are under `chrome/`. To test them, you can repeatedly modify GN files and re-run ninja until you get a successful build; ninja is smart enough to incrementally build with GN changes.

**Comment by HarukaMa** [comment]
It seems that I was not reading readme correctly and was not applying platform-specific patches. I thought safe browsing patches was in main repo from the parent issue, but apparently they are now scattered to platform ones.

I think there should be some extra mentions of the patches in different platform repos in [docs/building.md](https://github.com/Eloston/ungoogled-chromium/blob/master/docs/building.md) (I was following it as I was building chromium using official ways), as it currently only mentions the patches in the main repo, and apparently they alone are not sufficient now. It seems that I would need to merge those with the platform patches then apply from there.

This issue can be closed.

**Comment by Eloston** [comment]
> I thought safe browsing patches was in main repo from the parent issue, but apparently they are now scattered to platform ones.

Yeah, unfortunately we don't have any good policies or guidelines to dictate what should go into the main repo and what should go into the platform repo. I think the patches in the main repo work OOTB for Linux Desktop configurations.

> I think there should be some extra mentions of the patches in different platform repos in docs/building.md (I was following it as I was building chromium using official ways), as it currently only mentions the patches in the main repo, and apparently they alone are not sufficient now. It seems that I would need to merge those with the platform patches then apply from there.

Yeah, that's a good idea. I'll note that.
