### ISSUE TITLE
Need help with GitHub action

### ISSUE THREAD

**Issue by anshul78** [ungoogled-software/ungoogled-chromium-macos#49]
I am trying to build the binary using actions, but facing some issues.

This is the [workflow file](https://github.com/anshul78/ungoogled-chrome-mac/blob/master/.github/workflows/build.yml).

**Comment by kramred** [comment]
It might be that your run got terminated because of the [time limit](https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits) – although it states up to 6 hours execution time, the error message in [your log](https://github.com/anshul78/ungoogled-chrome-mac/runs/755241165) could indicate that the virtual machine was terminated.
Maybe there is/was an error in the calculation of the duration start: 2020-06-09T19:29, end: 2020-06-10T00:44; or something else caused the virtual machine to terminate early.

**Comment by anshul78** [comment]
I had rerun the same build. So the previous logs are not available. But that run terminated around 4 hour mark. This run too, it terminated before 6 hour mark.

Any idea how to modify the code to circumvent the 6 hour limit? Can the build script be broken into 2 or more parts?

**Comment by kramred** [comment]
> Any idea how to modify the code to circumvent the 6 hour limit?

As long as you're not using your own machines/VMs I think this cannot be done, as GitHub imposes that limit and they actually have to pay for the compute resources.

--- 

> Can the build script be broken into 2 or more parts

Maybe. Although it might be quite tricky to achieve that. See also the discussion here: https://github.com/Eloston/ungoogled-chromium/issues/1062

**Comment by jstkdng** [comment]
The idea for splitting is to upload the built sources as an artifact and then have another job download the artifact and continue building. I have set up this workflow that achieves that.
https://github.com/jstkdng/ungoogled-chromium-archlinux/blob/master/.github/workflows/build.yml
@kramred Github doesnt pay anything as it is owned by microsoft and actions use azure vms.

**Comment by kramred** [comment]
@anshul78 – I've followed @jstkdng example and set up a workflow for building Ungoogled Chromium using GitHub Actions, see https://github.com/kramred/ungoogled-chromium-macos/tree/build_on_github
I'm waiting for the final version to finish building and will then open a pull request on the main repo for macOS.
Soon we should have binaries directly from GitHub Actions, and you can also use the workflow to build them yourself.

I'll update in 12-14 h. 

It already worked [here](https://github.com/kramred/ungoogled-chromium-macos/actions/runs/165510480) if you want to grab that binary.  
Build times were in the range of 11 to 13 hours.
