### ISSUE TITLE
Unattended SCRIPT

### ISSUE THREAD

**Issue by lemons990** [ungoogled-software/ungoogled-chromium-macos#51]
I think you should include an unattended script like this one:

[unattended.sh.zip](https://github.com/ungoogled-software/ungoogled-chromium-macos/files/4800875/unattended.sh.zip)

**Comment by Eloston** [comment]
Thanks. I don't think it's appropriate to include the script as-is in ungoogled-chromium-macos since it changes the user's machine.

Perhaps you'd like to add your script to the newly created https://github.com/ungoogled-software/contrib?
