### ISSUE TITLE
Incoming UDP connection from google-analytics.com

### ISSUE THREAD

**Issue by kramred** [ungoogled-software/ungoogled-chromium-macos#75]
So, this happened to me today: Search on duckduckgo.com for "google ui guidelines"
https://duckduckgo.com/?q=google+ui+guidelines&ia=web

Open first 3 hits in tabs:
https://developers.google.com/assistant/interactivecanvas/design
https://developers.google.com/photos/library/guides/ux-guidelines
https://developers.google.com/mobile-data-plan/ui_guidelines

Get an incoming connection warning from little snitch:
from 142.250.184.14 on UDP port 58040

![UDP_google_analytics](https://user-images.githubusercontent.com/16719551/112630388-6f7bf800-8e2d-11eb-817e-9404eed203e4.png)

I could not reproduce this afterwards. 

I'm leaving this here as a note that there may be more (google) connection types hidden in the code that are not yet disabled by a patch.

**Comment by Eloston** [comment]
It's not really clear what your exact setup is, or how your traffic analyzer works. From what I can see, you opened Google-owned webpages, so I'm not surprised there is some analytics traffic happening.

You can try opening DevTools to the Network tab before visiting those webpages to see if the webpage is establishing connections.

**Comment by kramred** [comment]
[Little snitch](https://www.obdev.at/products/littlesnitch/index.html) is an application-based firewall for macOS.

My setup includes uBlock origin and uMatrix with rather strict blocking defaults and the console shows the connection attempts to google-analytics.com with `ERR_FAILED` (as they should be blocked by uBlock origin) – see below.

That's why I was surprised to see a UDP connection attempt from `142.250.184.14`, which was probably falsely assigned to google-analytics.com by little snitch and may just be one of the google servers' outgoing IPs that I was connecting to.

This UDP message would probably have been processed in the context of the tab/window with the google page opened – and not by the chromium browser itself (e.g. as a potential way to bypass connection limitations by extensions)

Anyway, as I cannot find a way to reproduce it and it's probably not related to ungoogled-chromium I'll close this issue now.

![uBlock](https://user-images.githubusercontent.com/16719551/112728791-d7f7d180-8f20-11eb-9739-019f7a8f4408.png)
![console](https://user-images.githubusercontent.com/16719551/112728792-d8906800-8f20-11eb-93cf-7eccbba0532d.png)

**Comment by Eloston** [comment]
The UDP traffic may also be Quic traffic. It won't be easy to tell unless you have a tool that can inspect and identify packet payloads. I know Wireshark is able to identify Quic traffic.
