### ISSUE TITLE
Cookies deleted upon update

### ISSUE THREAD

**Issue by kytta** [ungoogled-software/ungoogled-chromium-macos#87]
Since the last two versions or so, I have a problem with updating my web browser. Every time I update it, my cookies are being deleted. Weirdly enough, it's _only_ the cookies. History, LocalStorage, IndexedDB, bookmarks — everything is there, but the cookies aren't. As a consequence, I get logged out on every website that I have :(

I use the [Homebrew build](https://formulae.brew.sh/cask/eloston-chromium), so I apologize in advance if I submit this issue in a wrong repository. Maybe you can help me out with trying to debug this issue. Perhaps @frodera or @kramred know what could be wrong?

**Comment by kramred** [comment]
This could have various reasons. Does this also occur when quitting the browser or only on update/upgrade?

- Check the settings: chrome://settings/cookies?search=clear+cookies
  - "Clear cookies and site data when you close all windows" might be switched on
- Check the flag `clear-data-on-exit`: `chrome://flags/#clear-data-on-exit`

Might also be a (partly) corrupted profile, you'd have to try with a new, clean profile if the issue persists.

I personally have "Clear cookies and site data when you close all windows" switched on and added exceptions for specific sites; so I would not have noticed a change in the default behaviour (although for the sites where I allow cookies to persist it works also after upgrading, I think)

**Comment by kytta** [comment]
Nope, I double-checked: the cookies aren't being cleaned on exit, but precisely after `brew upgrade` :/

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently and probably lost its significance — closing.
If you have any more information to add, let us know.
