### ISSUE TITLE
Can we get a security patch push pls

### ISSUE THREAD

**Issue by shahjugal** [ungoogled-software/ungoogled-chromium-macos#88]
Can we get 98 release for mac it has few important security fixes. it would be great for mac users to get this update as it's been quiet a while since we got last update.

**Comment by kramred** [comment]
See: https://github.com/Eloston/ungoogled-chromium/#automated-or-maintained-builds
which lists `brew` as a way for macOS to "automatically" stay up to date, is uses this formula:
* https://formulae.brew.sh/cask/eloston-chromium that (mostly) points to
* https://github.com/kramred/ungoogled-chromium-macos/releases - releases build by GitHub Actions
