### ISSUE TITLE
Mac OS M1 - 101.0.4951.64-1 the latest version for now

### ISSUE THREAD

**Issue by loadcorp** [ungoogled-software/ungoogled-chromium-macos#89]
When you plan to update the Chrome for MacOS 64-bit ARM?

Thanks in advance.

**Comment by kramred** [comment]
Here is the GitHub Actions release for: [101.0.4951.64-1.1_arm64](https://github.com/kramred/ungoogled-chromium-macos/releases/tag/101.0.4951.64-1.1_arm64__1652357504)

When v102 is released, which will probably happen tomorrow, a GitHub Actions build for that release will be started and if it succeeds it will be available for download ~26 h later.

It is also available in the package manager [Homebrew](https://brew.sh/), via `brew install --cask eloston-chromium`, see [here](https://formulae.brew.sh/cask/eloston-chromium#default)

**Comment by wzxu** [comment]
@kramred Will we get the arm64 build for 102.0.5005.61? It's currently x86-64 only.

**Comment by kramred** [comment]
[Here](https://github.com/kramred/ungoogled-chromium-macos/releases/tag/102.0.5005.63-1.1_arm64__1654078408) is the latest version for arm64, which should include all changes from [102.0.5005.61-3](https://github.com/ungoogled-software/ungoogled-chromium/releases/tag/102.0.5005.61-3) and also uses chromium 102.0.5005.63 sources
