### ISSUE TITLE
Repository maintenance 

### ISSUE THREAD

**Issue by networkException** [ungoogled-software/ungoogled-chromium-macos#90]
This repository is currently unmaintained, as such we are considering to add people to the team as described in https://github.com/ungoogled-software/ungoogled-chromium/blob/master/docs/repo_management.md#teams-in-the-ungoogled-software-organization with access to this repository.

@kramred You have been doing great work maintaining macOS packaging on your fork to the same (in my opinion quite high) standards that we have for Windows and Arch Linux packaging in this organisation. Would you be willing to upstream the work as a maintainer here? I sadly only just saw #84 as I wasn't watching activity until now.

See also https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/144 and https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/301

**Comment by networkException** [comment]
CC @ungoogled-software/core (not sure who of you is watching here either)

**Comment by kramred** [comment]
1. Yes, I'd be willing to function as an official maintainer of the `ungoogled-chromium-macos` repo.

Lately I've been using my own fork of the `ungoogled-chromium` repo, which is still very similar to the main repo, for building on/for macOS. It already includes e.g. the [PR#1845](https://github.com/ungoogled-software/ungoogled-chromium/pull/1845).

__Question:__

I suppose it would be best to keep/revert to the official main `ungoogled-chromium` repo inside the official `ungoogled-chromium-macos` repo, what do you think?

---

2. Building the binaries: this has been done for a long time from my repo using GitHub Actions. I guess most users are managing their installation via `brew`, [which lists](https://formulae.brew.sh/cask/eloston-chromium) about 900 downloads per month.

__Question:__

I have a slight preference towards keeping the building of the binaries in my repo, at least for the next 1-2 major versions; after this transition period (with notice of the upcoming changes for the maintainer of the brew formula) I think it would be best to transfer the GitHub Actions binary building to the main `ungoogled-chromium-macos` repo and also have the releases there; would you agree with that or prefer to have the builds and releases in the main `ungoogled-chromium-macos` repo sooner?

**Comment by networkException** [comment]
> Yes, I'd be willing to function as an official maintainer of the `ungoogled-chromium-macos` repo.

:tada: 

> I suppose it would be best to keep/revert to the official main `ungoogled-chromium` repo inside the official `ungoogled-chromium-macos` repo, what do you think?

Yep thats definitely preferred. If modifications are documented I wouldn't have an issue with a separate branch here though.

> I think it would be best to transfer the GitHub Actions binary building to the main `ungoogled-chromium-macos` repo and also have the releases there; would you agree with that or prefer to have the builds and releases in the main `ungoogled-chromium-macos` repo sooner?

I don't think we are in a hurry, especially considering the latest commit here has been made over a year ago. So just take however much time you need for transitioning

**Comment by networkException** [comment]
Permissions should be set up now, can you close this issue as a test @kramred?

**Comment by kramred** [comment]
Closing, as permission have been put in place and are working.

**Comment by networkException** [comment]
Ah one little thing: When moving updating the link to point to this repo or the main patchset repo would be nice too https://github.com/Homebrew/homebrew-cask/blob/8de35f47d1a46de55e199b7a8489abd368e4e168/Casks/eloston-chromium.rb#L16
