### ISSUE TITLE
No update via Homebrew

### ISSUE THREAD

**Issue by 99thim** [ungoogled-software/ungoogled-chromium-macos#97]
Hello, I am not getting any repo update since version 108.0.5359.125 with Homebrew back in December which is confirmed on Homebrew page. You are not providing any updates via homebrew anymore?

Homebrew page(https://formulae.brew.sh/cask/eloston-chromium#default)
Name: Ungoogled Chromium
Google Chromium, sans integration with Google
https://ungoogled-software.github.io/ungoogled-chromium-binaries/
[/api/cask/eloston-chromium.json (JSON API)](https://formulae.brew.sh/api/cask/eloston-chromium.json)
[Cask code](https://github.com/Homebrew/homebrew-cask/blob/-/Casks/eloston-chromium.rb) on GitHub

Current version: [108.0.5359.125-1.1,1671136997](https://github.com/kramred/ungoogled-chromium-macos/releases/download/108.0.5359.125-1.1_x86-64__1671136997/ungoogled-chromium_108.0.5359.125-1.1_x86-64-macos.dmg)

**Comment by networkException** [comment]
@kramred sadly doesn't have time anymore, see https://github.com/ungoogled-software/ungoogled-chromium/pull/2214#pullrequestreview-1254141943

As such we're effectively looking for a new maintainer

**Comment by 99thim** [comment]
I see. Hopefully someone can take over. Anyway thank you for all time spent on this project!

**Comment by replete** [comment]
FYI just installed `Version 110.0.5481.177 (Official Build, ungoogled-chromium) (x86_64)` via homebrew. Thank you kindly

**Comment by Gribnif** [comment]
Has there been any progress on finding a new maintainer? The main project is currently at 111.0.5563.65 and contains a number of security updates not present here.

**Comment by 99thim** [comment]
Sad really they could not continue
