### ISSUE TITLE
Updating to 110

### ISSUE THREAD

**Issue by implicitfield** [ungoogled-software/ungoogled-chromium-macos#99]
I've looked at updating these patches to support ```chromium-110.0.5481.177```, and while there aren't too many changes needed, I feel that some of them may warrant discussion.

# 1. Debian Patches

In my opinion, these could all be dropped, save for ```patches/debian_buster/disable/installer.patch```, which could go to the upstream ```ungoogled-chromium``` repo, since there's nothing macOS-specific about it.

The [Debian Chromium repo](https://salsa.debian.org/chromium-team/chromium) no longer ships any of these patches, and while most of them still apply, they seem to have no impact when building with the latest LLVM toolchain. (Discussed in the next section.)

I'm not sure if ```patches/inox-patchset/fix-cfi-failures-with-unbundled-libxml.patch``` is needed either. Replacing all uses of ```XmlFree``` with ```free``` seems a bit odd. I don't have an unbundled libxml to test this with, though.

# 2. Toolchain Requirements

Building with LLVM 15 is currently broken. Either https://github.com/chromium/chromium/commit/cb5ad37 needs to be reverted, or the [odd initialization](https://github.com/chromium/chromium/commit/cb5ad37#diff-4f8bd3e1578fbfe105e2f3c248d35ecad20e3cf2b7a3703047afaf87045ef15dR1385) should be changed to work with LLVM 15.

Alternatively, the minimum LLVM version could be bumped to LLVM 16, though it remains unreleased as of yet. (It's not yet available in homebrew, so maybe the build script could handle building it?) However, building with LLVM 16 is broken on arm without https://github.com/chromium/chromium/commit/9f43d82. (See https://bugs.chromium.org/p/chromium/issues/detail?id=1405048)

I'd prefer requiring LLVM 16 for maximum compatibility, but supporting older releases shouldn't be too difficult (yet.)

**Comment by PF4Public** [comment]
If you manage to <s>make it great again</s> get it building again, you have my approval :)

Indeed there is no need for keeping patches which are unrelated to the platform. I would be cautious about sticking to llvm-16 since it is not released yet, but I'm not using macOS in any way, so you may know better.
